# Generated by Django 2.0.2 on 2018-02-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server1c',
            name='port',
        ),
        migrations.AddField(
            model_name='server1c',
            name='port',
            field=models.ManyToManyField(null=True, to='servers.Port'),
        ),
    ]
