# Generated by Django 2.0.2 on 2018-02-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20180228_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server1c',
            name='name',
            field=models.GenericIPAddressField(primary_key=True, serialize=False),
        ),
    ]
